// NOPs ui colors
#define UI		#DAD8CE
#define UI_2	#E6E4D9
#define UI_3	#CECDC3
#define BG		#FFFCF0
#define BG_2	#F2F0E5
#define TX		#100F0F
#define TX_2	#6F6E69
#define TX_3	#B7B5AC
#define PAPER	#FFFCF0
// NOPs colors
#define FRE_2 	 #D14D41
#define FRE	     #AF3029

#define FOR_2 	 #DA702C
#define FOR	     #BC5215

#define FYE_2 	 #D0A215
#define FYE	     #AD8301

#define FGR_2 	 #879A39
#define FGR	     #66800B

#define FCY_2 	 #3AA99F
#define FCY	     #24837B

#define FBL_2 	 #4385BE
#define FBL	     #205EA6

#define FPU_2 	 #8B7EC8
#define FPU	     #5E409D

#define FMA_2 	 #CE5D97
#define FMA	     #A02F6F


#define GREY(g) g g g
#define BLACK                       BG
#define WHITE                       PAPER

#define RED                         FRE
#define GREEN                       FGR
#define BLUE                        FBL
#define CYAN                        FCY
#define YELLOW                      FYE
#define MAGENTA                     FMA

#define PINK                        FMA_2
#define MINT                        0.8 1 0.8
#define LTBLUE                      0.5 0.5 1
#define LTYELLOW                    1 1 0.5
#define ORANGE                      FOR
#define BROWN			                  FYE_2
