// NOPs ui colors
#define UI		#592202  // hallow 
#define UI_2	#A64F03  // hallow
#define UI_3	#BF6B04  // hallow
#define BG		#833e08  // hallow
#define BG_2	#672f05  // hallow
#define TX		#040701  // hallow
#define TX_2	#0b1102  // hallow
#define TX_3	#0d1402  // hallow
#define PAPER	#FFFCF0 
// NOPs colors
#define FRE 	 #D14D41
#define FRE_2	 #AF3029
#define FOR 	 #DA702C
#define FOR_2	 #BC5215
#define FYE 	 #D0A215
#define FYE_2	 #AD8301
#define FGR 	 #0b1102 // hallow
#define FGR_2	 #66800B
#define FCY 	 #3AA99F
#define FCY_2	 #24837B
#define FBL 	 #5E1742
#define FBL_2	 #262626
#define FPU 	 #8B7EC8
#define FPU_2	 #5E409D
#define FMA 	 #CE5D97
#define FMA_2	 #A02F6F

#define GREY(g) g g g
#define BLACK                       BG
#define WHITE                       PAPER

#define RED                         FRE
#define GREEN                       FGR
#define BLUE                        FBL
#define CYAN                        FCY
#define YELLOW                      FYE
#define MAGENTA                     FMA

#define PINK                        FMA_2
#define MINT                        0.8 1 0.8
#define LTBLUE                      0.5 0.5 1
#define LTYELLOW                    1 1 0.5
#define ORANGE                      FOR
#define BROWN                       FYE_2
