CanvasPromptFont:		    NetworkFont
CanvasPromptFontSize:		0.2
CanvasMinGridSpacing:		0.2
CanvasGridPointSize:		0.03
CanvasFlashMessageFont:		NetworkFont
CanvasFlashMessageFontSize:	0.4 // adjusted

PaletteMarginInches:		    0.04 // adjusted
ColorPaletteCellMarginInches:	0.01
ShapePaletteCellMarginInches:	0.04

BackgroundImageMaxControlSizeInches: 0.2
BackgroundImageControlSize:	1.0
BackgroundImageControlHMargin:	0.2
BackgroundImageControlVMargin:	0.3

GraphOverlayTextHMarginInches:	0.2
GraphOverlayTextVMarginInches:	0.0
GraphOverlayTextAlpha:		0.55
GraphOverlayLeftFont:		NetworkFont
GraphOverlayLeftFontSizeInches:	0.35
GraphOverlayCenterFont:		NetworkFont
GraphOverlayCenterFontSizeInches: 0.25
GraphOverlayRightFont:		BoldFont
GraphOverlayRightFontSizeInches: 0.35

GraphFootprintMinRadiusInches:	0.3
GraphFootprintMinOverviewRadiusInches:	0.2
GraphFootprintSizeScale:	1.25
GraphFootprint0Thickness:	0.4
GraphFootprint1Thickness:	0.2
GraphFootprint2Thickness:	0.11
GraphFootprint3Thickness:	0.0136

GraphDependencyExternalHeight:	0.10
GraphDependencyExternalWidth:	0.07
GraphDependencyExternalHOffset:	0.00
GraphDependencyExternalVOffset:	0.05
GraphDependencyCountMargin:	0.005
GraphDependencyCountFont:	NetworkFont
GraphDependencyCountSize:	0.14

GraphPreSelectionAlpha:		0.4
GraphLayerColorAlpha:		0.2
GraphLayerColorWireWidth:	0.54
GraphLayerColorOutlineDist:	0.15

GraphItemNameFont:		NetworkFont
GraphItemNameSize:		0.225
GraphItemDescriptionFont:	NetworkFont
GraphItemDescriptionSize:	0.15
GraphCommentMaxWidth:		6.0
GraphDescriptiveNameMaxWidth:	0.0
GraphContextOptionDepsMaxWidth:	5.0
GraphLopLastModifiedPrimMaxWidth:	0.0

GraphFlyoutBackgroundBlendFlagOn:	0.78
GraphFlyoutBackgroundBlendFlagOff:	0.95
GraphFlyoutOuterRadius:		0.9
GraphFlyoutInnerRadiusScale:	0.6
GraphFlyoutFlagIndicatorScale:	0.1
GraphFlyoutFlagIconScale:	0.3
GraphMinFlyoutOuterRadiusInches:0.45
GraphMinFlyoutInnerRadiusInches:0.2
GraphFlyoutRegionAlpha:		0.6
GraphFlyoutNonInteractiveAlpha:	0.4

GraphDotRadius:					0.09
GraphDotPinInnerFraction:		0.35
GraphDotPinOuterFraction:		0.65
GraphMaxDotRadiusInches:		0.1
GraphWireStubLength:			0.20
GraphWireStubRadius:			0.035
GraphWireStubSelectedBorder:	0.02
GraphWireArrowLength:			0.15
GraphWireArrowAspectRatio:	    0.5
GraphWireMinArrowLengthInches:	0.05
GraphWireMaxArrowLengthInches:	0.6
GraphWireLongFadedAlpha:		0.6
GraphWireLongerFadedAlpha:	    0.1
GraphWireLongFadeLength:		5.0
GraphWireLongerFadeLength:	    10.0
GraphWireMinCurveRadius:		0.05
GraphWireMaxCurveRadius:		0.3
GraphWireRoundedCurveRadius:	0.3
GraphWireParmVopStubWidth:		0.2
GraphWireParmVopStubHeight:		0.1
GraphWireNodeSelectionBlend:	0.4

GraphMinConnectorSpace:			0.03
GraphConnectorRadius:			0.045
GraphConnectorPickRadius:		0.15
GraphConnectorLabelOffset:		0.08
GraphConnectorIndicatorSize:	0.045
GraphItemCornerRadius:		0.1
GraphBorderWidth:		    2.5
GraphHighDPIBorderWidth:	3
GraphOverviewBorderWidth:	2
GraphHighDPIOverviewBorderWidth:    3

GraphCop2PreviewMaxSize:		128
GraphCop2PreviewMinAspect:	    1.0
GraphCop2PreviewMaxAspect:	    5.0
GraphCop2BottomBarHeight:		0.15
GraphCop2BottomBarMarginLeft:	0.1
GraphCop2BottomBarMarginRight:	0.1
GraphCop2BottomButtonSize:	    0.1
GraphCop2PlaneNameFont:			InputFont

GraphVopPreviewHeight:				1.0
GraphVopConnectorHeight:			0.15
GraphVopConnectorFontHeight:	0.12
GraphVopConnectorDotScale:		0.25
GraphVopConnectorNameIndent:	0.1
GraphVopConnectorNameFont:		NetworkFont
GraphVopBottomBarHeight:			0.15
GraphVopBottomBarMarginLeft:	0.1
GraphVopBottomBarMarginRight:	0.1
GraphVopBottomButtonSize:			0.1
GraphVopBottomButtonSpacing:	0.1
GraphVopGroupExpanderWidth:		0.05
GraphVopGroupExpanderHeight:	0.08
GraphVopTopSpacing:			0.03
GraphVopBottomSpacing:	0.05
GraphVopGroupSpacing:		0.08
GraphVopFlyoutVerticalShift:	-0.1

GraphShopConnectorHeight:	0.15
GraphShopConnectorFontHeight:	0.12
GraphShopConnectorDotScale:	0.25
GraphShopConnectorNameIndent:	0.08
GraphShopConnectorNameFont:	NetworkFont
GraphShopTopSpacing:			0.03
GraphShopBottomSpacing:		0.05
GraphShopFlyoutVerticalShift:	-0.1

GraphSubnetShadowOffset:	-0.0505

GraphBypassColorBlend:		0.9
GraphBypassNameColorBlend:0.4
GraphBypassConnectorColorBlend:	0.6
GraphBypassBorderColorBlend:		0.35
GraphBypassIconAlpha:			0.3
GraphBypassBadgeAlpha:		0.4

// DIM settings
GraphOutsideCookSetColorBlend:		0.2
GraphOutsideCookSetNameColorBlend:	0.2
GraphOutsideCookSetConnectorColorBlend:	0.5

GraphNameHSpacing:	0.05
GraphNameVSpacing:	0.06
GraphBadgeSize:			0.2
GraphBadgeDotRadius:	0.06
GraphBadgeHIndent:		0.05
GraphBadgeHSpacing:		0.22
GraphBadgeVSpacingBelow:	-0.01
GraphBadgeVSpacingAbove:	0.04
GraphNodeTypeVSpacingAbove:	0.10
GraphDescriptionVSpacingBelow:	-0.17
GraphDescriptionVSpacingBelowNoBadges:	-0.04
GraphDescriptionVSpacingAbove:	0.38
GraphDescriptionVSpacingAboveNoBadges:	0.04
GraphDescriptionWidth:	2.0
GraphDescriptionLines:	3

GraphLargeBadgeMinSizeInches:		0.2
GraphLargeBadgeOverviewMinSizeInches:	0.15
GraphLargeBadgeSize:			0.7
GraphLargeBadgeLeftShift:	-0.2
GraphLargeBadgeTopShift:	0.0
GraphLargeBadgeStackLeftShift:	-0.6
GraphLargeBadgeStackTopShift:		0.0

// FOR LOOPS AND SUCH
GraphHullOffset:		0.3 // adjusted
GraphHullNestedOffset:	0.15
GraphHullAlpha:			0.2

GraphPerfGlowMaxSize:		0.4
GraphPerfGlowMaxSizeInches:	0.4
GraphPerfGlowMinSizeInches:	0.1
GraphPerfGlowMaxOverviewSizeInches:	0.2
GraphPerfGlowMinOverviewSizeInches:	0.1

GraphNetworkBoxOffset:		0.15
GraphNetworkBoxSpaceForNames:	1.6
GraphNetworkBoxMinWidth:	1.5
GraphNetworkBoxTitleHeight:	0.25
GraphNetworkBoxTitleIndent:	0.15
GraphNetworkBoxMinMaxSize:	0.25
GraphNetworkBoxMinMaxIndent:	0.05
GraphNetworkBoxAlpha:		0.25
GraphNetworkBoxTitleAlpha:	0.3
GraphNetworkBoxTitleFont:	BoldFont
GraphNetworkBoxTitleSize:	0.255
GraphNetworkBoxEscapeVel:	2.0

GraphStickyNoteMinWidth:		2.5
GraphStickyNoteTitleHeight:	0.225
GraphStickyNoteTitleIndent:	0.05
GraphStickyNoteTextHMargin:	0.05
GraphStickyNoteTextVMargin:	0.05
GraphStickyNoteMinMaxSize:	0.25
GraphStickyNoteMinMaxIndent:	0.05
GraphStickyNoteAlpha:		0.4
GraphStickyNoteTitleAlpha:	0.9
GraphStickyNoteFont:		NetworkFont
GraphStickyNoteSize:		0.225
GraphStickyNoteTitleFont:	NetworkFont
GraphStickyNoteTitleSize:	0.225

GraphPdgProgressMaxRadius:		0.2
GraphPdgProgressMinRadius:		0.1
GraphPdgProgressRadiusRatio:	0.8
GraphPdgProgressDefaultRadius:  0.2

GraphPdgSummarySizeRatio:	2.0
GraphPdgSummaryTextSize:	0.45

GraphTaskGraphWorkItemsSpacing: 4
GraphTaskGraphMaxWires:         10

NodePopupBG:                    #1C1B1A
NodePopupBasicBG:               #100F0F
NodePopupListBG:                #205EA6
NodePopupNeedsRefreshBG:        #343331

TaskPopupBG:                    #151713
TaskPopupBasicBG:               #0f1926
