#include "NodeGraphNOPsSettings.inc"

PaletteBackground:	UI_2
PaletteSelected:	YELLOW
ShapePaletteShape:	TX

BackgroundImageLocate:		WHITE
BackgroundImageBorder:		YELLOW
BackgroundImageBrightness:	YELLOW
BackgroundImageLink:		GREY(0.8)

GraphOverlayLeftText:		0.2 0.9 0.9
GraphOverlayCenterText:		TX_2
GraphOverlayRightText:		FOR_2

GraphBackground:			UI
GraphOverviewBackground: 	BG_2
GraphOverviewViewRegion: 	FBL_2
GraphOverviewBorder:		BG
GraphPromptText:			FYE
GraphGridLines:				UI
GraphGridPoints:			UI_3

GraphNameText:                  TX
GraphNodeTypeText:              FBL
GraphCommentText:               FCY
GraphDescriptiveNameText:	    FGR
GraphContextOptionDepsText:	    FBL
GraphLopLastModifiedPrimText:   FOR
GraphLopLayerCountText:         FOR_2
GraphOutputForViewText:		    #6DB4BD
GraphDetailIdText:		        #6DB4BD
GraphNetworkBoxText:		    TX
GraphNetworkBoxTextDark:	    BG
GraphNetworkBoxNameText:        #76A8E1
GraphIndirectText:              TX
GraphIndirectTextDark:          BG

GraphItemBorder:		BLACK
GraphMinimizeButton:	GREY(0.8)

GraphTemplateFlag:				FMA
GraphSelectableTemplateFlag:	FMA_2
GraphBypassFlag:		FYE
GraphRenderFlag:		FPU
GraphDisplayFlag:		FBL_2
GraphOutputFlag:		FOR_2
GraphSelectableFlag:	FGR_2
GraphExportFlag:		#FFA600
GraphHiddenFlag:		FPU
GraphAudioFlag:			0.0 0.5 0.5
GraphThumbnailFlag:		0.35 0.6 0.2
GraphLockFlag:			RED
GraphSoftLockFlag:		#C4 E3 61 
GraphDebugFlag:			FCY
GraphMaterialFlag:		FOR_2
GraphDisplayAndRenderFlag:	FBL
GraphDisplayAndOutputFlag:	0.75 0.95 0.36
GraphFilterFlag:			#55FFC1

GraphDisplayHighlight:	#44679A
GraphExportHighlight:		#734670
GraphRenderHighlight:		#9273CB
GraphOutputHighlight:		#6B5634
GraphTemplateHighlight:	#734670
GraphFilterHighlight:		#298966

GraphDopObjectData:		0.65	0.65	0.65
GraphDopData:			    0.50	0.80	0.50
GraphDopRelData:		  0.20	0.60	0.20
GraphDopSolverData:		0.7	0.5	0.9
GraphDopAnyData:		  0.9	0.9	0.9
GraphSopHeightfield:	#25aa8e
GraphSopConstraints:	#D879D8
GraphSopDomain:		    #6bcae2
GraphSopRestGeometry:	0.584   0.776   1.0
GraphSopCapturePose:	0.6     0.6     0.6
GraphSopAnimatedPose:	1.0     0.725   0.0

GraphConnector:			    TX
GraphConnectorLabel:    TX
GraphConnectorError:    FRE
GraphCop2MaskInput:	    0.50 0.80 0.50
GraphWire:			        FBL
GraphWireUnused:		    FOR_2
GraphWireError:			    RED
GraphWireLoopBack:	    0.3 0.3 1.0
GraphWireSelection:	    YELLOW
GraphWireNodeSelection:	YELLOW
GraphWireLongFaded:	    FCY_2
GraphWireLongerFaded:		FPU
GraphWireStub:			    FCY
GraphWireStubSelection:	YELLOW
GraphWireCut:			      RED
GraphWireCutPath:		    FOR_2
GraphWireStitchStart:		FPU
GraphWireStitchEnd:	    FPU
GraphSpareWire:			    FPU
GraphParmOverrideWire:	#FFA500

GraphDependency:						#9A6955
GraphDependencyEndAffector:	#668E4A
GraphDependencyExternalIn:	GREY(0.8)
GraphDependencyExternalOut:	GREY(0.8)

GraphPickFill:			UI_3
GraphPreSelection:	0.75 0.86 1.0
GraphItemCurrent:   HSV 3 .7 0.95
GraphItemCurrentNonSelected:FCY_2
GraphItemSelection:					FOR
GraphItemSelectionContrast:	BLACK
GraphItemContentsSelection:	#6E780C

GraphSnapLine:							FRE

GraphFlyoutBackgroundFlagOn:	BLACK
GraphFlyoutBackgroundFlagOff:	BLACK
GraphFlyoutEdgeFlagOff:				GREY(0.3)
GraphFlyoutInfo:              GREY(0.1)
GraphFlyoutWarning:           0.2 0.2 0.0
GraphFlyoutError:             0.2 0.0 0.0

GraphDotPinAccent:		       FBL

GraphCop2PreviewBackground:  GREY(0.1)
GraphCop2BottomButtonEnabled:GREY(0.1)

GraphVopConnectorGroupName:   WHITE
GraphVopConnectorBackground:	GREY(0.25)
GraphVopBottomButtonEnabled:	GREY(0.1)
GraphVopBottomButtonDisabled:	GREY(0.6)

GraphShopConnectorBackground:	GREY(0.1)

GraphSubnetShadow1:      FOR_2
GraphSubnetShadowBlend1: 0.7
GraphSubnetShadow2:		   FBL
GraphSubnetShadowBlend2: .5

GraphErrorBadgeDot:		  ERROR
GraphChildErrorBadgeDot:ERROR
GraphWarningBadgeDot:		0.77 0.60 0.04
GraphMessageBadgeDot:		0.05 0.45 1.00
GraphCommentBadgeDot:		0.15 0.67 0.64
GraphNodeLockedBadgeDot:1.00 0.35 0.43
GraphNodeUnloadBadgeDot:0.60 0.65 0.73
GraphNodeHasDataBadgeDot:0.45 0.75 0.45
GraphNeedsCookBadgeDot:	0.97 0.91 0.11
GraphHdaLockedBadgeDot:	0.43 0.47 0.48
GraphHdaUnlockedBadgeDot:0.98 0.49 0.55
GraphHdaDelaySyncBadgeDot:0.70 0.70 0.70
GraphTimeDependentBadgeDot:0.72 0.91 0.53
GraphVexCachedBadgeDot:		 #FF5AD2
GraphVexCachableBadgeDot:	 #AA3E8C
GraphNotCompilableBadgeDot:#E5B985
GraphConstraintsBadgeDot:	 #97C473
GraphKinematicsBadgeDot:	 #FF9370
GraphHasTakeDataBadgeDot:	 #979797
GraphNodeUnloadBadgeDot:   #D19F9F
GraphNodeHasDataBadgeDot:  #9FABD1
Graph64bitBadgeDot:        #AC68CC
GraphPdgDynamicBadgeDot:	 #E5C8FF
GraphUnloadedPayloadsBadgeDot:#EDC486
GraphPopulationMaskBadgeDot:	#A06B9A
GraphDiveableBadgeDot:		 #73d216
GraphLoadFromDiskBadgeDot: #dceefaff
GraphPdgMQServerAuthBadgeDot:	#448519
GraphPdgMQClientsAuthBadgeDot:#448519

GraphPdgProgressOutline:	WHITE
GraphPdgProgressPrecook:	#324D59
GraphPdgProgressCooking:	#B8E986
GraphPdgProgressCooked:		#4D623F
GraphPdgProgressWarning:	#EBF802
GraphPdgProgressError:		#FF3300
GraphPdgProgressIncomplete: #75876A

GraphPdgProgressErrorCircle: #D0021B
GraphPdgProgressErrorFill:   #730000
GraphPdgProgressNormalFill:  #232323

GraphPdgSummaryBackground:  GREY(0.18)
GraphPdgSummaryFilterOn:    #FFD42A
GraphPdgSummaryWorkItemCooked:		#73945D
GraphPdgSummaryWorkItemCooking:		#B8E986
GraphPdgSummaryWorkItemWaiting:		#879889
GraphPdgSummaryWorkItemUncooked:	GREY(0.5)
GraphPdgSummaryWorkItemFailed:		#EE5A6C
GraphPdgSummaryWorkItemCancelled:	#EBB502

GraphTaskGraphBackground:			GREY(0.1)
GraphTaskGraphBorder:				  GREY(0.7)
GraphTaskGraphSeeMore:				GREY(0.9)
GraphTaskGraphWorkItemCooked:		#529232
GraphTaskGraphWorkItemCached:		#529232
GraphTaskGraphWorkItemCooking:	#ADFF49
GraphTaskGraphWorkItemWaiting:	#354B60
GraphTaskGraphWorkItemUncooked:	GREY(0.5)
GraphTaskGraphWorkItemFailed:		#FF3300
GraphTaskGraphWorkItemCancelled:#69511B
GraphTaskGraphWorkItemSelected:	#FFD42A
GraphTaskGraphWorkItemHovered:	#33EEFF
GraphTaskGraphWorkItemAncestor:	#99FF79
GraphTaskGraphWorkItemDescendant:#2AFFCB
GraphTaskGraphNormalWire:			  GREY(0.9)
GraphTaskGraphMappedWire:			  #80FFA2
GraphTaskGraphIndirectWire:			#D9DD70

GraphTaskGraphWorkItemPerfFast: #009166
GraphTaskGraphWorkItemPerfMed:  #f6ff00
GraphTaskGraphWorkItemPerfSlow: #ff9000
GraphTaskGraphWorkItemPerfNA:		GREY(0.35)

GraphTaskGraphStatusBarFailed:	  #FF9C9C
GraphTaskGraphStatusBarCancelled: #F7DF1B
GraphTaskGraphStatusBarCooked:	  #529232
GraphTaskGraphStatusBarCooking:	  #B7DF86
GraphTaskGraphStatusBarWaiting:	  GREY(0.6)
GraphTaskGraphStatusBarEmpty:	    GREY(0.2)

GraphTaskGraphLogError:		    #D04548
GraphTaskGraphLogWarning:	    #B8B834

GraphTaskPageRect:            #D8D8D8

GraphTopBottomButtonEnabled:	GREY(0.1)
GraphTopBottomButtonDisabled:	GREY(0.6)

GraphLopLayerOutline:		GREY(0.6)
GraphLopLayerColor1:		0.30 0.70 0.20
GraphLopLayerColor2:		0.60 0.40 0.20
GraphLopLayerColor3:		0.90 0.10 0.20
GraphLopLayerColor4:		0.30 0.20 0.30
GraphLopLayerColor5:		0.60 0.20 0.60
GraphLopLayerColor6:		0.90 0.20 0.90
GraphLopLayerColor7:		0.20 0.70 0.30
GraphLopLayerColor8:		0.20 0.40 0.60
GraphLopLayerColor9:		0.20 0.10 0.90

